service: ner-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

package:
  exclude:
    - .vscode/**
    - node_modules/**
    - __pycache__/**
    - .ipynb_checkpoints/**
    - (*).ipynb

functions:
  recognize-named-entites:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30 
    events:
      - http:
          path: ner
          method: post

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true 
    zip: true
    noDeploy: []
    useDownloadCashe: true 
    useStaticCache: true 

plugins:
  - serverless-python-requirements
