
service: hello-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

# you can add packaging information here
package:
  exclude:
    - .vscode/**

functions:
  hello-function:
    handler: handler.hello
    memorySize: 128
    timeout: 30 
    events:
      - http:
          path: hello-path
          method: get
